function mayor(edad){
    if (edad >= 13 && edad <= 15){
        return("* Irán * indonesia *Yemen");
        } else if  (edad === 16){
        return("* Irán * indonesia *Yemen * Birmania *  Birmania* Camboya * Cuba * Kirguistán * Reino Unido * Escocia * Vietnam");
        } else if (edad >= 17 && edad <= 18){
        return("* Irán * indonesia *Yemen * Birmania * Birmania * Camboya * Cuba * Kirguistán * Reino Unido * Escocia * Vietnam * Corea del Norte * Timor Oriental * Albania * Alberta * Alemania * Andorra * Antigua y Barbuda * Armenia * Australia * Austria ​* Azerbaiyán * Bahamas ​* Bangladés * Barbados ​* Bélgica ​* Belice ​* Bielorrusia ​* Bolivia* Bosnia y Herzegovina ​* Botsuana* Brasil * Brunéi * Bulgaria * Burundi * Bután * Canadá ​* Chile * China ​* Dependencias de la Corona * Isla del Príncipe Eduardo * Manitoba * Ontario * Saskatchewan * Territorio Británico de Ultramar * Angola * Argentina * Catar * China continental * Chipre * Ciudad del Vaticano * Colombia * Costa Rica * Croacia  ​* Dinamarca * Dominica * Ecuador * El Salvador ​* Eslovaquia * Eslovenia * España ​* Estonia * Filipinas ​* Finlandia ​* Fiyi * Francia ​* Gales ​* Georgia * Ghana * Gibraltar ​* Grecia ​* Guatemala * Guernsey * Guinea * Guinea-Bisáu * Guyana * Haití * Hong Kong * Hungria * India * Inglaterra * Irak * Irlanda * Irlanda del Norte * Isla de Man * Islandia * Israel * Italia * Jamaica * Japón * Jersey * Jordania * Kazajistán * Kenia * Laos * Liechtenstein * Lituania * Luxemburgo * Macao * Macedonia del Norte * Malasia ​ * Malaui ​ * Malta ​ ​ * Mauricio * Mauritania * México ​ * Moldavia * Mónaco * Mongolia * Montenegro * Namibia ​ * Nepal * Nigeria * Noruega ​ * Omán ​ ​* Países Bajos ​  ​* Pakistán ​  ​* Pakistán ​  ​* Palaos ​* Palestina* Panamá* Paraguay ​* Perú* Polonia ​  ​* Portugal* Quebec* Reino Unido ​* República Checa ​  ​* República Dominicana ​* Ruanda* Rumania* Rusia ​  ​* San Cristóbal y Nieves ​* San Vicente y las Granadinas* Serbia* Seychelles* Singapur* Siria ​ ​ ​* Somalia* Sri Lanka ​* Sudáfrica  ​* Sudán ​* Suecia ​* Suiza ​* Taiwán* Tayikistán ​ * Trinidad y Tobago * Túnez ​ * Turquía ​ * Ucrania ​ * Uganda ​ * Uruguay * Uzbekistán ​ * Venezuela ​ * Yibuti ​ * Zimbabue");
        } else if (edad === 19){
        return("* Irán * indonesia *Yemen * Birmania * Birmania * Camboya * Cuba * Kirguistán * Reino Unido * Escocia * Vietnam * Corea del Norte * Timor Oriental * Albania * Alberta * Alemania * Andorra * Antigua y Barbuda * Armenia * Australia * Austria ​* Azerbaiyán * Bahamas ​* Bangladés * Barbados ​* Bélgica ​* Belice ​* Bielorrusia ​* Bolivia* Bosnia y Herzegovina ​* Botsuana* Brasil * Brunéi * Bulgaria * Burundi * Bután * Canadá ​* Chile * China ​* Dependencias de la Corona * Isla del Príncipe Eduardo * Manitoba * Ontario * Saskatchewan * Territorio Británico de Ultramar * Angola * Argentina * Catar * China continental * Chipre * Ciudad del Vaticano * Colombia * Costa Rica * Croacia  ​* Dinamarca * Dominica * Ecuador * El Salvador ​* Eslovaquia * Eslovenia * España ​* Estonia * Filipinas ​* Finlandia ​* Fiyi * Francia ​* Gales ​* Georgia * Ghana * Gibraltar ​* Grecia ​* Guatemala * Guernsey * Guinea * Guinea-Bisáu * Guyana * Haití * Hong Kong * Hungria * India * Inglaterra * Irak * Irlanda * Irlanda del Norte * Isla de Man * Islandia * Israel * Italia * Jamaica * Japón * Jersey * Jordania * Kazajistán * Kenia * Laos * Liechtenstein * Lituania * Luxemburgo * Macao * Macedonia del Norte * Malasia ​ * Malaui ​ * Malta ​ ​ * Mauricio * Mauritania * México ​ * Moldavia * Mónaco * Mongolia * Montenegro * Namibia ​ * Nepal * Nigeria * Noruega ​ * Omán ​ ​* Países Bajos ​  ​* Pakistán ​  ​* Pakistán ​  ​* Palaos ​* Palestina* Panamá* Paraguay ​* Perú* Polonia ​  ​* Portugal* Quebec* Reino Unido ​* República Checa ​  ​* República Dominicana ​* Ruanda* Rumania* Rusia ​  ​* San Cristóbal y Nieves ​* San Vicente y las Granadinas* Serbia* Seychelles* Singapur* Siria ​ ​ ​* Somalia* Sri Lanka ​* Sudáfrica  ​* Sudán ​* Suecia ​* Suiza ​* Taiwán* Tayikistán ​ * Trinidad y Tobago * Túnez ​ * Turquía ​ * Ucrania ​ * Uganda ​ * Uruguay * Uzbekistán ​ * Venezuela ​ * Yibuti ​ * Zimbabue * Argelia  ​* Canadá * Alabama  ​* Columbia Británica * Corea del Sur 5 ​* Estados Unidos * Nebraska  ​* Nueva Escocia * Nuevo Brunswick * Nunavut * Terranova y Labrador * Territorios del Noroeste * Yukón");
        } else if (edad === 20){
        return("* Irán * indonesia *Yemen * Birmania * Birmania * Camboya * Cuba * Kirguistán * Reino Unido * Escocia * Vietnam * Corea del Norte * Timor Oriental * Albania * Alberta * Alemania * Andorra * Antigua y Barbuda * Armenia * Australia * Austria ​* Azerbaiyán * Bahamas ​* Bangladés * Barbados ​* Bélgica ​* Belice ​* Bielorrusia ​* Bolivia* Bosnia y Herzegovina ​* Botsuana* Brasil * Brunéi * Bulgaria * Burundi * Bután * Canadá ​* Chile * China ​* Dependencias de la Corona * Isla del Príncipe Eduardo * Manitoba * Ontario * Saskatchewan * Territorio Británico de Ultramar * Angola * Argentina * Catar * China continental * Chipre * Ciudad del Vaticano * Colombia * Costa Rica * Croacia  ​* Dinamarca * Dominica * Ecuador * El Salvador ​* Eslovaquia * Eslovenia * España ​* Estonia * Filipinas ​* Finlandia ​* Fiyi * Francia ​* Gales ​* Georgia * Ghana * Gibraltar ​* Grecia ​* Guatemala * Guernsey * Guinea * Guinea-Bisáu * Guyana * Haití * Hong Kong * Hungria * India * Inglaterra * Irak * Irlanda * Irlanda del Norte * Isla de Man * Islandia * Israel * Italia * Jamaica * Japón * Jersey * Jordania * Kazajistán * Kenia * Laos * Liechtenstein * Lituania * Luxemburgo * Macao * Macedonia del Norte * Malasia ​ * Malaui ​ * Malta ​ ​ * Mauricio * Mauritania * México ​ * Moldavia * Mónaco * Mongolia * Montenegro * Namibia ​ * Nepal * Nigeria * Noruega ​ * Omán ​ ​* Países Bajos ​  ​* Pakistán ​  ​* Pakistán ​  ​* Palaos ​* Palestina* Panamá* Paraguay ​* Perú* Polonia ​  ​* Portugal* Quebec* Reino Unido ​* República Checa ​  ​* República Dominicana ​* Ruanda* Rumania* Rusia ​  ​* San Cristóbal y Nieves ​* San Vicente y las Granadinas* Serbia* Seychelles* Singapur* Siria ​ ​ ​* Somalia* Sri Lanka ​* Sudáfrica  ​* Sudán ​* Suecia ​* Suiza ​* Taiwán* Tayikistán ​ * Trinidad y Tobago * Túnez ​ * Turquía ​ * Ucrania ​ * Uganda ​ * Uruguay * Uzbekistán ​ * Venezuela ​ * Yibuti ​ * Zimbabue * Argelia  ​* Canadá * Alabama  ​* Columbia Británica * Corea del Sur 5 ​* Estados Unidos * Nebraska  ​* Nueva Escocia * Nuevo Brunswick * Nunavut * Terranova y Labrador * Territorios del Noroeste * Yukón * Taiwán * Tailandia");
        } else if (edad >= 21){
        return("* Irán * indonesia *Yemen * Birmania * Birmania * Camboya * Cuba * Kirguistán * Reino Unido * Escocia * Vietnam * Corea del Norte * Timor Oriental * Albania * Alberta * Alemania * Andorra * Antigua y Barbuda * Armenia * Australia * Austria ​* Azerbaiyán * Bahamas ​* Bangladés * Barbados ​* Bélgica ​* Belice ​* Bielorrusia ​* Bolivia* Bosnia y Herzegovina ​* Botsuana* Brasil * Brunéi * Bulgaria * Burundi * Bután * Canadá ​* Chile * China ​* Dependencias de la Corona * Isla del Príncipe Eduardo * Manitoba * Ontario * Saskatchewan * Territorio Británico de Ultramar * Angola * Argentina * Catar * China continental * Chipre * Ciudad del Vaticano * Colombia * Costa Rica * Croacia  ​* Dinamarca * Dominica * Ecuador * El Salvador ​* Eslovaquia * Eslovenia * España ​* Estonia * Filipinas ​* Finlandia ​* Fiyi * Francia ​* Gales ​* Georgia * Ghana * Gibraltar ​* Grecia ​* Guatemala * Guernsey * Guinea * Guinea-Bisáu * Guyana * Haití * Hong Kong * Hungria * India * Inglaterra * Irak * Irlanda * Irlanda del Norte * Isla de Man * Islandia * Israel * Italia * Jamaica * Japón * Jersey * Jordania * Kazajistán * Kenia * Laos * Liechtenstein * Lituania * Luxemburgo * Macao * Macedonia del Norte * Malasia ​ * Malaui ​ * Malta ​ ​ * Mauricio * Mauritania * México ​ * Moldavia * Mónaco * Mongolia * Montenegro * Namibia ​ * Nepal * Nigeria * Noruega ​ * Omán ​ ​* Países Bajos ​  ​* Pakistán ​  ​* Pakistán ​  ​* Palaos ​* Palestina* Panamá* Paraguay ​* Perú* Polonia ​  ​* Portugal* Quebec* Reino Unido ​* República Checa ​  ​* República Dominicana ​* Ruanda* Rumania* Rusia ​  ​* San Cristóbal y Nieves ​* San Vicente y las Granadinas* Serbia* Seychelles* Singapur* Siria ​ ​ ​* Somalia* Sri Lanka ​* Sudáfrica  ​* Sudán ​* Suecia ​* Suiza ​* Taiwán* Tayikistán ​ * Trinidad y Tobago * Túnez ​ * Turquía ​ * Ucrania ​ * Uganda ​ * Uruguay * Uzbekistán ​ * Venezuela ​ * Yibuti ​ * Zimbabue * Argelia  ​* Canadá * Alabama  ​* Columbia Británica * Corea del Sur 5 ​* Estados Unidos * Nebraska  ​* Nueva Escocia * Nuevo Brunswick * Nunavut * Terranova y Labrador * Territorios del Noroeste * Yukón * Taiwán * Tailandia * Baréin  ​* Camerún   ​* Costa de Marfil   ​* Egipto   ​* Emiratos Árabes Unidos * Estados Unidos * Gabón ​* Granada ​* Honduras  ​nota ​* Kuwait ​* Lesoto * Madagascar * Misisipi ​* Níger * Puerto Rico * Samoa * Singapur ​* Suazilandia ​* Zambia");        
        }else {
            return("No eres mayor de edad en ningún país.")
        }
}
let dato = mayor(16)
        console.log(dato);